version: '3'

services:
  mdi_mechanic:
    #build: .
    image: "mdi_mechanic/mdi_mechanic"
    command: bash -c "bash /repo/MDI_Mechanic/.temp/docker_mdi_mechanic.sh"
    volumes:
      - "${MDIMECH_WORKDIR}:/repo"
      - "${MDIMECH_PACKAGEDIR}:/MDI_Mechanic"
    networks:
      mdinet:
        aliases:
          - driverhost
  engine:
    #build: ../../user
    image: "mdi_mechanic/lammps"
    command: bash -c "bash /repo/MDI_Mechanic/.temp/docker_mdi_engine.sh"
    volumes:
      - "${MDIMECH_WORKDIR}:/repo"
      - "${MDIMECH_PACKAGEDIR}:/MDI_Mechanic"
    networks:
      mdinet:
        aliases:
          - enginehost
    depends_on:
      - mdi_mechanic

networks:
  mdinet:
    driver: "bridge"