# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      MDIMECH_CI: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install MDI Mechanic
        run: |
          sudo apt-get update
          pip install wheel
          pip install pyyaml
          mkdir mechbuild
          cd mechbuild
          git clone https://github.com/MolSSI-MDI/MDI_Mechanic.git
          cd MDI_Mechanic
          pip install .
          cd ../..

      - name: Run CI Using MDI Mechanic
        run: python -c "import mdimechanic; mdimechanic.ci()"
