name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Set up Python '${{ matrix.python-version }}'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: |
        python -m pip install .

    - name: Perform docker setup
      if: matrix.os == 'ubuntu-latest'
      uses: docker-practice/actions-setup-docker@master

    - name: Test whether MDI Mechanic can start a project
      if: matrix.os == 'ubuntu-latest'
      run: |
        set -x
        mkdir ~/start_test
        cd ~/start_test
        mdimechanic startproject --enginereport
#        mdimechanic build
#        ls /home/runner/.local/lib/python3.8/site-packages/mdimechanic/docker/ssh


#    - name: Check for files
#      if: matrix.os == 'ubuntu-latest'
#      run: |
#        ls /home/runner/.local/lib/python3.8/site-packages/mdimechanic/docker/ssh


    - name: Build the ELECTRIC MDI driver
      if: matrix.os == 'ubuntu-latest'
      run: |
        set -x
        mkdir ~/electric_test
        cd ~/electric_test
        git clone https://github.com/MolSSI-MDI/ELECTRIC_container.git
        cd ELECTRIC_container
        mdimechanic build


    - name: Test the ELECTRIC MDI driver
      if: matrix.os == 'ubuntu-latest'
      run: |
        set -x
        cd ~/electric_test/ELECTRIC_container
        mdimechanic run --name tcp


    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
